In [5]:
%run ../base_setup.ipynb

Foundation: 2.11.018
Transition: 2.11.024
Engines   : 2.03.027
Behavioral: 2.06.037

In [6]:
sample_size = 10000
seed = None

-------------------------
## Synthetic Builder

In [7]:
builder = SyntheticBuilder.from_env('members')

### Run the Pipeline  save the Schema and show the Canonical Report

In [8]:
# set the version
builder.set_version(VERSION)

# run the pipeline
builder.run_synthetic_pipeline(size=sample_size)

# report
builder.canonical_report(builder.load_synthetic_canonical(), stylise=True)

### Save Reports

In [9]:
builder.save_report_canonical(report_connector_name=builder.REPORT_INTENT, report=builder.report_intent(stylise=False))
builder.save_report_canonical(report_connector_name=builder.REPORT_CATALOG, report=builder.report_column_catalog(stylise=False))

-------------------------
## Members Transition

In [10]:
tr = Transition.from_env('members')

In [11]:
# set the version
tr.set_version(VERSION)

# run the pipeline
tr.run_transition_pipeline()

# report
tr.canonical_report(tr.load_clean_canonical(), stylise=True)

### Save Reports

In [12]:
tr.save_report_canonical(report_connector_name=tr.REPORT_DICTIONARY, report=tr.canonical_report(tr.load_clean_canonical(), stylise=False))
tr.save_report_canonical(report_connector_name=tr.REPORT_SUMMARY, report=tr.report_quality_summary(stylise=False))
tr.save_report_canonical(report_connector_name=tr.REPORT_PROVENANCE, report=tr.report_provenance(stylise=False))
tr.save_report_canonical(report_connector_name=tr.REPORT_FIELDS, report=tr.report_attributes(tr.load_clean_canonical(), stylise=False))

-------------------------
## Clinincal Transition

In [13]:
tr_cln = Transition.from_env('cln_members')

In [14]:
# set the version
tr_cln.set_version(VERSION)

# run the pipeline
tr_cln.run_transition_pipeline()

# report
tr_cln.canonical_report(tr_cln.load_clean_canonical(), stylise=True)

### Save Reports

In [15]:
tr_cln.save_report_canonical(report_connector_name=tr_cln.REPORT_DICTIONARY, report=tr_cln.canonical_report(tr_cln.load_clean_canonical(), stylise=False))
tr_cln.save_report_canonical(report_connector_name=tr_cln.REPORT_SUMMARY, report=tr_cln.report_quality_summary(stylise=False))
tr_cln.save_report_canonical(report_connector_name=tr_cln.REPORT_PROVENANCE, report=tr_cln.report_provenance(stylise=False))
tr_cln.save_report_canonical(report_connector_name=tr_cln.REPORT_FIELDS, report=tr_cln.report_attributes(tr_cln.load_clean_canonical(), stylise=False))

-------------------------
## Preferences Transition

In [16]:
tr_prf = Transition.from_env('prf_members')

In [17]:
# set the version
tr_prf.set_version(VERSION)

# run the pipeline
tr_prf.run_transition_pipeline()

# report
tr_prf.canonical_report(tr_prf.load_clean_canonical(), stylise=True)

### Save Reports

In [18]:
tr_prf.save_report_canonical(report_connector_name=tr_prf.REPORT_DICTIONARY, report=tr_prf.canonical_report(tr_prf.load_clean_canonical(), stylise=False))
tr_prf.save_report_canonical(report_connector_name=tr_prf.REPORT_SUMMARY, report=tr_prf.report_quality_summary(stylise=False))
tr_prf.save_report_canonical(report_connector_name=tr_prf.REPORT_PROVENANCE, report=tr_prf.report_provenance(stylise=False))
tr_prf.save_report_canonical(report_connector_name=tr_prf.REPORT_FIELDS, report=tr_prf.report_attributes(tr_prf.load_clean_canonical(), stylise=False))